### ISSUE TITLE
macvtap-cni pods panicking - signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x88945c

### ISSUE THREAD

**Issue by davmin** [kubevirt/macvtap-cni#115]
**What happened**:
Daemonset pods on all nodes crashing with error `signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x88945c`

**What you expected to happen**:
Pods to run without crashing.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy macvtap-cni to cluster via cluster-network-addons operator.

**Anything else we need to know?**:
bare metal talos cluster on intel nucs
k8s: 1.27.4
linux: 6.1.61-talos
kernel module macvtap loaded

pod logs
```
I1226 06:05:23.905858   21412 manager.go:42] Starting device plugin manager
I1226 06:05:23.905904   21412 manager.go:46] Registering for system signal notifications
I1226 06:05:23.906078   21412 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
I1226 06:05:23.906128   21412 manager.go:60] Starting Discovery on new plugins
I1226 06:05:23.906146   21412 manager.go:66] Handling incoming signals
I1226 06:05:23.906180   21412 lister.go:67] Read configuration map[]
I1226 06:05:23.908043   21412 manager.go:71] Received new list of plugins: [bond0 teql0 eth0 eth1 thunderbolt0 thunderbolt1]
I1226 06:05:23.908108   21412 manager.go:110] Adding a new plugin "thunderbolt1"
I1226 06:05:23.908115   21412 lister.go:167] Creating device plugin with config {Name:thunderbolt1 LowerDevice:thunderbolt1 Mode:bridge Capacity:100}
I1226 06:05:23.908164   21412 plugin.go:64] thunderbolt1: Starting plugin server
I1226 06:05:23.908169   21412 plugin.go:95] thunderbolt1: Starting the DPI gRPC server
I1226 06:05:23.908213   21412 manager.go:110] Adding a new plugin "eth0"
I1226 06:05:23.908231   21412 lister.go:167] Creating device plugin with config {Name:eth0 LowerDevice:eth0 Mode:bridge Capacity:100}
I1226 06:05:23.908280   21412 plugin.go:64] eth0: Starting plugin server
I1226 06:05:23.908288   21412 plugin.go:95] eth0: Starting the DPI gRPC server
I1226 06:05:23.908238   21412 manager.go:110] Adding a new plugin "bond0"
I1226 06:05:23.908341   21412 manager.go:110] Adding a new plugin "eth1"
I1226 06:05:23.908368   21412 lister.go:167] Creating device plugin with config {Name:bond0 LowerDevice:bond0 Mode:bridge Capacity:100}
I1226 06:05:23.908391   21412 plugin.go:64] bond0: Starting plugin server
I1226 06:05:23.908398   21412 plugin.go:95] bond0: Starting the DPI gRPC server
I1226 06:05:23.908390   21412 lister.go:167] Creating device plugin with config {Name:eth1 LowerDevice:eth1 Mode:bridge Capacity:100}
I1226 06:05:23.908401   21412 manager.go:110] Adding a new plugin "teql0"
I1226 06:05:23.908441   21412 plugin.go:64] eth1: Starting plugin server
I1226 06:05:23.908436   21412 lister.go:167] Creating device plugin with config {Name:teql0 LowerDevice:teql0 Mode:bridge Capacity:100}
I1226 06:05:23.908451   21412 plugin.go:95] eth1: Starting the DPI gRPC server
I1226 06:05:23.908480   21412 plugin.go:64] teql0: Starting plugin server
I1226 06:05:23.908491   21412 plugin.go:95] teql0: Starting the DPI gRPC server
I1226 06:05:23.908492   21412 plugin.go:113] thunderbolt1: Serving requests...
I1226 06:05:23.908489   21412 manager.go:110] Adding a new plugin "thunderbolt0"
I1226 06:05:23.908537   21412 plugin.go:113] bond0: Serving requests...
I1226 06:05:23.908526   21412 lister.go:167] Creating device plugin with config {Name:thunderbolt0 LowerDevice:thunderbolt0 Mode:bridge Capacity:100}
I1226 06:05:23.908584   21412 plugin.go:64] thunderbolt0: Starting plugin server
I1226 06:05:23.908606   21412 plugin.go:95] thunderbolt0: Starting the DPI gRPC server
I1226 06:05:23.908637   21412 plugin.go:113] eth1: Serving requests...
I1226 06:05:23.908644   21412 plugin.go:113] eth0: Serving requests...
I1226 06:05:23.908683   21412 plugin.go:113] teql0: Serving requests...
I1226 06:05:23.908752   21412 plugin.go:113] thunderbolt0: Serving requests...
I1226 06:05:33.910356   21412 plugin.go:129] eth0: Registering the DPI with Kubelet
I1226 06:05:33.910376   21412 plugin.go:129] thunderbolt1: Registering the DPI with Kubelet
I1226 06:05:33.910448   21412 plugin.go:129] bond0: Registering the DPI with Kubelet
I1226 06:05:33.910504   21412 plugin.go:129] eth1: Registering the DPI with Kubelet
I1226 06:05:33.910567   21412 plugin.go:129] thunderbolt0: Registering the DPI with Kubelet
I1226 06:05:33.910703   21412 plugin.go:129] teql0: Registering the DPI with Kubelet
I1226 06:05:33.910892   21412 plugin.go:141] eth0: Registration for endpoint macvtap.network.kubevirt.io_eth0
I1226 06:05:33.910969   21412 plugin.go:141] thunderbolt1: Registration for endpoint macvtap.network.kubevirt.io_thunderbolt1
I1226 06:05:33.911010   21412 plugin.go:141] bond0: Registration for endpoint macvtap.network.kubevirt.io_bond0
I1226 06:05:33.911012   21412 plugin.go:141] thunderbolt0: Registration for endpoint macvtap.network.kubevirt.io_thunderbolt0
I1226 06:05:33.911159   21412 plugin.go:141] teql0: Registration for endpoint macvtap.network.kubevirt.io_teql0
I1226 06:05:33.911228   21412 plugin.go:141] eth1: Registration for endpoint macvtap.network.kubevirt.io_eth1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x88945c]

goroutine 105 [running]:
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).MarshalToSizedBuffer(...)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.pb.go:1545
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).Marshal(0x0, 0x9b7860, 0x0, 0x7f28929f9b20, 0x0, 0x9ae501)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.pb.go:1528 +0x7c
google.golang.org/grpc/encoding/proto.codec.Marshal(0x9b7860, 0x0, 0x967660, 0x7f28929f6918, 0x40a49f, 0xc000010000, 0x94f140)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x199
google.golang.org/grpc.encode(0x7f28929f6918, 0xdb5858, 0x9b7860, 0x0, 0xdb5858, 0xc000010000, 0x963240, 0x98b800, 0x7f2892bc57d0)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/rpc_util.go:538 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc000532000, 0xa8a018, 0xc0002d8780, 0xc0005ec000, 0x9b7860, 0x0, 0x0, 0x0, 0xc00012011c, 0x0, ...)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/server.go:983 +0x91
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000532000, 0xa8a018, 0xc0002d8780, 0xc0005ec000, 0xc00052c120, 0xd7a620, 0x0, 0x0, 0x0)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/server.go:1229 +0x625
google.golang.org/grpc.(*Server).handleStream(0xc000532000, 0xa8a018, 0xc0002d8780, 0xc0005ec000, 0x0)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000026060, 0xc000532000, 0xa8a018, 0xc0002d8780, 0xc0005ec000)
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/github.com/kubevirt/macvtap-cni/vendor/google.golang.org/grpc/server.go:857 +0x1fd
Stream closed EOF for cluster-network-addons/macvtap-cni-q2xl8 (macvtap-cni)
```

**Comment by davmin** [comment]
Was running an old version of cnao, updating resolved the issue.
